### PR TITLE
Add callback to attacker

### PR DESCRIPTION
**Pull request by bgweber**
#### Background

Adds an optional callback function to the attacker that is called synchronously after each hit.

#### Checklist

- [ ] Git commit messages conform to [community standards](http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html).
- [ ] Each Git commit represents meaningful milestones or atomic units of work.
- [ ] Changed or added code is covered by appropriate tests.

### CODE REVIEW

**Comment by tsenart** [comment]
You can read from the results channel and act on each result there. Why do we *also* need a callback?

**Comment by bgweber** [comment]
If we can get this from the channel, then this is not needed. Can you share an example of this approach?

**Comment by tsenart** [comment]
https://github.com/tsenart/vegeta

**Comment by bgweber** [comment]
Thanks, closing.

**Pull request closed without merging**
