### PR TITLE
[WIP] Add connect-to flag

### PR DESCRIPTION
**Pull request by AntonioMA**
#### Background

This implement the feature requested in https://github.com/tsenart/vegeta/issues/575

#### Checklist

- [X] Git commit messages conform to [community standards](http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html).
- [X] Each Git commit represents meaningful milestones or atomic units of work.
- [X] Changed or added code is covered by appropriate tests.

### CODE REVIEW

**Comment by jfreeland** [comment]
this would be pretty handy

**Comment by upgle** [comment]
There is quite a difference in performance due to DNS cache. I need this feature too!

**Comment by tsenart** [comment]
Thanks for the contribution. I think I'd rather add the capability of Vegeta caching DNS responses for a configurable duration instead of this. It's my understand that would also solve your problem of overloading your corporate DNS server.

**Comment by dkegel-fastly** [comment]
I still need this; curl doesn't make us set up a special dns server, vegeta shouldn't, either, IMHO.

**Pull request closed without merging**
