### PR TITLE
Added windows example

### PR DESCRIPTION
**Pull request by odino**
I had the misfortune of having to run vegeta on windows this morning :)

I went crazy a bunch of time just to understand what I was doing wrong so I thought it might be helpful to include an example around..

### CODE REVIEW

**Comment by tsenart** [comment]
Hm, I wouldn't add Windows examples in there as Vegeta is mainly targeted at Unix systems. Windows users ought to know Powershell and understand that the examples need to be adapted.

But hey: http://techcrunch.com/2016/03/30/be-very-afraid-hell-has-frozen-over-bash-is-coming-to-windows-10/

:D

**Comment by odino** [comment]
alright!

**Comment by tsenart** [comment]
Sorry! :/

**Comment by odino** [comment]
no worries, it happens! It took me 2 mins to open a PR and, if it was worth
it, it would have been nice to include it. But overall I agree that
win-specific stuff is generally a pain in the ass so no probs! Beauty of OS!

Cheers! :)

On Wed, Apr 20, 2016 at 10:51 PM, Tomás Senart <notifications@github.com>
wrote:

> Sorry! :/
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/tsenart/vegeta/pull/176#issuecomment-212556548>
>



-- 
Nadalin Alessandro
http://www.linkedin.com/in/alessandronadalin
www.odino.org
www.twitter.com/_odino_

**Pull request closed without merging**
