### PR TITLE
Swap "of need" to "of a need" in README

### PR DESCRIPTION
**Pull request by ciarand**
sorry

### CODE REVIEW

**Comment by tsenart** [comment]
What are you sorry for? :-)

**Comment by ciarand** [comment]
stupid PRs

**Comment by tsenart** [comment]
I wouldn't call descriptive PRs stupid. Although I'm fluent in English, it's not my native language. Would you please explain me why the form you suggest is more correct than the one before?

**Comment by ciarand** [comment]
Sure! Here's the original for reference (emphasis mine):

>Vegeta is a versatile HTTP load testing tool built **out of need** to drill HTTP services with a constant request rate

The problem is that the phrase "need to X" is a noun phrase, so you need a noun there. In the case above the `a` becomes the target of the noun phrase so the sentence becomes ok.

**Comment by tsenart** [comment]
Cool, thanks for elucidating :-)

**Comment by ciarand** [comment]
You're welcome, thanks for the awesome tool!

**Pull request merged**
