### PR TITLE
Add ARM 32bits architecture

### PR DESCRIPTION
**Pull request by carlosflorencio**
#### Background

To run inside a raspberry pi, the source code needs to be compiled for arm 32bits.

Tested on a raspberry pi 3b+ with the `HypriotOS/armv7` distro.

Are you able to provide the pre-compiled executable for ARM32 as well?

Thanks

#### Checklist

- [X] Git commit messages conform to [community standards](http://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html).
- [X] Each Git commit represents meaningful milestones or atomic units of work.
- [X] Changed or added code is covered by appropriate tests.

### CODE REVIEW

**Comment by tsenart** [comment]
> Are you able to provide the pre-compiled executable for ARM32 as well?

Yes, but for [which version](https://github.com/golang/go/wiki/GoArm)? All of them? If so, the `goreleaser.yml` file needs to be adapted for that.

**Comment by carlosflorencio** [comment]
The version `ARMv7` should do the trick.

**Comment by tsenart** [comment]
> The version ARMv7 should do the trick.

Can you then update the PR accordingly please (as to be explicit about this version)?

**Comment by carlosflorencio** [comment]
I've updated the `.goreleaser.yml`, please validate since I'm not familiar with GoReleaser.

**Pull request merged**
