### PR TITLE
Setup Github Actions based CI

### PR DESCRIPTION
**Pull request by tsenart**

### CODE REVIEW

**Comment by tsenart** [comment]
@bookmoons @fuzzitdev: Any clue how to fix this Fuzz Regression CI failure? https://github.com/tsenart/vegeta/pull/456/checks?check_run_id=276595658

**Comment by bookmoons** [comment]
Strange. I wonder if it's a Go 1.13 issue. Is it possible to get the fuzz stages running under Go 1.12?

**Comment by tsenart** [comment]
> Is it possible to get the fuzz stages running under Go 1.12?

I don't know, would have to check documentation. Do you have plans to support Go 1.13 though?

**Comment by bookmoons** [comment]
I haven't seen Fuzzit mention plans for 1.13. The example configures it to use 1.12:
https://github.com/fuzzitdev/example-go/blob/master/.travis.yml

I always force it to 1.12 in integrations to follow that pattern.

**Comment by bookmoons** [comment]
@yevgenypats Any ideas about this error? I haven't integrated with GitHub Actions before.

**Comment by tsenart** [comment]
Ping @bookmoons @yevgenypats. I really want to get out of Travis CI :D

**Pull request merged**
